/**
 * Bedrock Adapter
 * ---------------
 * Handles everything specific to Minecraft Bedrock Dedicated Server (BDS):
 *   - Spawning the native bedrock_server(.exe) binary
 *   - Parsing Bedrock console output (different format from Java servers)
 *   - Default server.properties for Bedrock
 *   - Installation from ZIP archive
 *
 * The rest of the system (processManager, WebSocket, file routes, backup routes)
 * is reused unchanged.
 */

'use strict';

const path = require('path');
const fs   = require('fs');

// ─── Constants ───────────────────────────────────────────────────────────────

const BEDROCK_EXECUTABLE_WIN   = 'bedrock_server.exe';
const BEDROCK_EXECUTABLE_LINUX = 'bedrock_server';

/**
 * Default server.properties for a fresh Bedrock server.
 * Port is injected at creation time.
 */
const DEFAULT_BEDROCK_PROPERTIES = `# Bedrock Dedicated Server — generated by MinePanel
server-name=MinePanel Server
gamemode=survival
force-gamemode=false
difficulty=easy
allow-cheats=false
max-players=20
online-mode=true
allow-list=false
server-port=19132
server-portv6=19133
enable-lan-visibility=true
view-distance=32
tick-distance=4
player-idle-timeout=30
max-threads=8
level-name=Bedrock level
level-seed=
default-player-permission-level=member
texturepack-required=false
content-log-file-enabled=false
compression-threshold=1
compression-algorithm=zlib
server-authoritative-movement=server-auth
network-compression-enabled=true
player-movement-score-threshold=20
player-movement-action-direction-threshold=0.85
player-movement-distance-threshold=0.3
player-movement-duration-threshold-in-ms=500
correct-player-movement=false
server-authoritative-block-breaking=false
chat-restriction=None
disable-player-interaction=false
client-side-chunk-generation-enabled=true
block-network-ids-are-hashes=true
disable-persona=false
disable-custom-skins=false
`;

// ─── Console Output Parser ────────────────────────────────────────────────────

/**
 * Bedrock log lines look like:
 *   [2024-07-15 12:00:00:123 INFO] Starting Server
 *   [2024-07-15 12:00:00:456 WARN] Level 'Bedrock level' is not found
 *
 * We annotate lifecycle events so users see clear status messages.
 */
function parseBedrockOutput(raw) {
    const line = raw.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

    // Server ready
    if (line.includes('Server started.') || line.includes('IPv4 supported')) {
        return line + '\n[MinePanel] ✔  Bedrock server is ready to accept connections.\n';
    }

    // Graceful shutdown
    if (line.includes('Server stop requested.') || line.includes('Quit correctly')) {
        return line + '\n[MinePanel] Bedrock server is shutting down...\n';
    }

    // Port already in use
    if (line.includes('Failed to bind') || line.includes('already in use')) {
        return line + '\n[MinePanel] ⚠  Port is already in use. Change server-port in server.properties.\n';
    }

    return line;
}

// ─── Installation helper ──────────────────────────────────────────────────────

/**
 * Extract the downloaded Bedrock ZIP into serverDir, write default configs,
 * and chmod the binary on Linux.
 *
 * @param {string} zipPath   - path to the downloaded .zip file
 * @param {string} serverDir - destination directory (already created)
 * @param {number} port      - port to write into server.properties
 */
async function installBedrock(zipPath, serverDir, port) {
    const AdmZip = require('adm-zip');
    const zip = new AdmZip(zipPath);
    zip.extractAllTo(serverDir, true /* overwrite */);

    // Write server.properties if not already present (fresh install)
    const propertiesPath = path.join(serverDir, 'server.properties');
    if (!fs.existsSync(propertiesPath)) {
        let props = DEFAULT_BEDROCK_PROPERTIES;
        props = props.replace(/^server-port=.*/m, `server-port=${port}`);
        fs.writeFileSync(propertiesPath, props, 'utf8');
    } else {
        // Update port in existing properties
        let props = fs.readFileSync(propertiesPath, 'utf8');
        props = props.replace(/^server-port=.*/m, `server-port=${port}`);
        fs.writeFileSync(propertiesPath, props, 'utf8');
    }

    // Ensure permissions.json exists (Bedrock equivalent of ops.json)
    const permsPath = path.join(serverDir, 'permissions.json');
    if (!fs.existsSync(permsPath)) {
        fs.writeFileSync(permsPath, '[]', 'utf8');
    }

    // Ensure allowlist.json exists
    const allowlistPath = path.join(serverDir, 'allowlist.json');
    if (!fs.existsSync(allowlistPath)) {
        fs.writeFileSync(allowlistPath, '[]', 'utf8');
    }

    // On Linux, chmod +x the binary
    if (process.platform !== 'win32') {
        const exePath = path.join(serverDir, BEDROCK_EXECUTABLE_LINUX);
        if (fs.existsSync(exePath)) {
            fs.chmodSync(exePath, 0o755);
        }
    }
}

// ─── Launch descriptor ────────────────────────────────────────────────────────

/**
 * Returns a launch descriptor understood by the patched getStartInfo() in
 * serverRoutes.js.  Instead of java + JVM args + jar, we return the native
 * binary path.  processManager.start() is called with the binary as both
 * the "javaPath" and "jarFile" so the existing signature stays intact.
 *
 * processManager spawns:  executable []  (no extra args needed for BDS)
 *
 * @param {Object} server    - DB row
 * @param {string} serverDir - absolute path to server directory
 * @returns {{ isBedrock, serverDir, executable, env, jarFile, customArgs, javaArgs }}
 */
function getBedrockLaunchDescriptor(server, serverDir) {
    const isWin = process.platform === 'win32';
    const exeName = isWin ? BEDROCK_EXECUTABLE_WIN : BEDROCK_EXECUTABLE_LINUX;
    const executable = path.join(serverDir, exeName);

    const env = { ...process.env };
    if (!isWin) {
        // BDS on Linux requires LD_LIBRARY_PATH to point at its own directory
        const existingLd = env.LD_LIBRARY_PATH || '';
        env.LD_LIBRARY_PATH = existingLd ? `${serverDir}:${existingLd}` : serverDir;
    }

    return {
        isBedrock: true,
        serverDir,
        executable,
        env,
        // These mirror the Java signature so processManager.start() needs no changes:
        jarFile: executable,    // "jar" = the binary itself
        customArgs: [],         // BDS takes no extra CLI args by default
        javaArgs: []            // no JVM flags
    };
}

/**
 * Returns true when server.software is a native Bedrock binary type
 * (bedrock or bedrock-preview), case-insensitive.
 */
function isBedrock(software) {
    if (typeof software !== 'string') return false;
    const s = software.toLowerCase();
    return s === 'bedrock' || s === 'bedrock-preview';
}

// ─── Exports ─────────────────────────────────────────────────────────────────

module.exports = {
    installBedrock,
    getBedrockLaunchDescriptor,
    parseBedrockOutput,
    isBedrock,
    DEFAULT_BEDROCK_PROPERTIES,
    BEDROCK_EXECUTABLE_WIN,
    BEDROCK_EXECUTABLE_LINUX
};
