name: Deploy React Vite to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write # Avem nevoie de write pentru a crea branch-ul gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./src/demo

      - name: Build project
        run: npm run build
        working-directory: ./src/demo

      - name: Deploy to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/demo/dist
